[package]
name = "aht20_rp_pico_example"
version = "1.0.0"
edition = "2021"

[dependencies]
aht20-driver = { path = "../.." }
cortex-m = "0.7.7"
cortex-m-rt = "0.7.3"
defmt = "0.3.8"
defmt-rtt = "0.4.1"
embedded-hal = "1.0.0"
fugit = "0.3.7"
panic-halt = "0.2.0"
rp-pico = "0.9.0"
